version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: SocketServer_app
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8080:8080"
    env_file:
      - .env.example
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env.example
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local